### ISSUE TITLE
To Do:

### ISSUE THREAD

**Issue by Xiocious** [josuf107/xioqbot#1]
[Brackets] are variables
- There are no spaces in an NNID, but spaces should be allowed in a MiiName.
- Capitalization should be "NNID" and "MiiName"
- "!smash teamclear" for clearing the team lists
- Slight adjustment to !info. Should say "| User: [name] | Position #[#] In Queue | NNID: [NNID] | MiiName: [MiiName] | W:L [W#]:[L#] |

- !info was showing "Position 0:1", was it using Win/Loss? (I think you fixed this)

- When it states who's next after someone plays, it should have ([MiiName]) after their name and if they need to be added, "+[NNID]"

I shouldn't include other things from the doc right? Also, I'll write other stuff here if need be. Msg me on Discord

**Comment by josuf107** [comment]
Ah each of these should be one issue. The issue list itself is kind of a To Do list. I'll break this one up so you can see what an issue should look like.

**Comment by josuf107** [comment]
Okay I created #2 #3 #4 #5 for the items in this issue. The queue position for !info was already fixed. I'm going to close this now.
