### ISSUE TITLE
Highlight users needing friendmes

### ISSUE THREAD

**Issue by josuf107** [josuf107/xioqbot#14]
In !list and whenever displaying next up or current players, show a plus sign next to their names.

Need to figure out what to do for teams.

**Comment by josuf107** [comment]
@Xiocious any notion what we should do for teams that contain users needing friendme?

**Comment by Xiocious** [comment]
Possibly the addition of a !team [name] command that would show the members and could show a plus sign there. 
If that's possible, then the team itself could have 1 or 2 +'s after it to let me know to check !team
Also, I noted in the doc upcoming players should have (MiiName) afterwards, but the !team [name] should also note their Mii Names. Maybe a formatting like:
"| Team Name | TwitchName & TwitchName | NNID & NNID | MiiName & Mii Name|"
Is that cool? The + would show after the Twitch name

**Comment by josuf107** [comment]
Went ahead and added the !team command. When displaying in the list the team name will have a + after it if any team members need friend mes.
