### ISSUE TITLE
Ruleset + stagelist commands

### ISSUE THREAD

**Issue by Xiocious** [josuf107/xioqbot#23]
I listed them in the test, but I'll list them here too
ruleset for Singles: "Singles Ruleset: 2 Stock, 6m Time, No Items, Legal Stages Only | Refer to !stagelist for legal stages."
ruleset for Doubles: "Doubles Ruleset: 3 Stock, 8m Time, No Items, Team Attack On, Legal Stages Only | Refer to !stagelist for legal stages."
!stagelist: "Legal Stages: Battlefield, FD(Omega Palutena’s), Smashville, Town and City, Duck Hunt, Dreamland, and Lylat."

**Comment by josuf107** [comment]
This is done and merged to master. I've added the Ready for Deploy label to indicate that a feature is in the code but not in the currently running bot. Once #16 is out I'll probably just put features right into the running bot once they're done, but at the moment restarting the bot has some unfortunate side-effects (resets everything except the user index).
