### ISSUE TITLE
Replace !index With New Information

### ISSUE THREAD

**Issue by Xiocious** [josuf107/xioqbot#36]
For Melee, it's unnecessary to hold a Nintendo Network ID (NNID) and Mii_Name, so it's better to make !index record the player's tag/in-game_name and preferred version of Dolphin (FM v5.9 or Slippi r18)

"!index smash_tag version" ( version= [5.9, Slippi] ) should replace the current "!index nnid miiname"

"!version [twitch name]" should be a command that states a user's preference: "[twitch name] prefers [Slippi r18, FM v5.9]."

Upon indexing, the bot should give confirmation while also letting the players know that they should have both FM v5.9 and Slippi r18:
"[Twitch name] has been indexed. Make sure to have both FM v5.9 and Slippi r18."

**Comment by josuf107** [comment]
Okay this will require changing the queue structure. Should I update the Migrate module so we can preserve the currently registered users with their win/loss records? I can match up existing users by their twitch username and modify their index entry to include their dolphin version. Or do you want to just start from scratch?

**Comment by josuf107** [comment]
@Xiocious said we have different viewers playing a different game, so it's okay to scrap the existing index. That makes it a lot easier. Dumped the old index to a CSV file for posterity.

**Comment by josuf107** [comment]
Per updates to slippi netplay we no longer need to mess with anything of this stuff. I'll open a follow up issue to change nnids/miinames to connect codes.
