### ISSUE TITLE
Change format for !info output

### ISSUE THREAD

**Issue by josuf107** [josuf107/xioqbot#4]
Make !info output look like "| User: [name] | Position #[#] In Queue | NNID: [NNID] | MiiName: [MiiName] | W:L [W#]:[L#] |

**Comment by Xiocious** [comment]
Actually, slight change: When the custom crews(made like teams) is a thing...
"| User: [name] | Position #[#] In Queue | Crew: [Custom Crew] | NNID: [NNID] | MiiName: [MiiName] | W:L [W#]:[L#] |"
It's just a crew note

**Comment by josuf107** [comment]
Should crew be present in every mode, or just crew mode?

**Comment by josuf107** [comment]
Answer is every mode

**Comment by josuf107** [comment]
Created #9 to add support for crew mode. Until then this should be good
