### ISSUE TITLE
Include MiiName(s) when displaying next up

### ISSUE THREAD

**Issue by josuf107** [josuf107/xioqbot#5]
When it states who's next after someone plays, it should have ([MiiName]) after their name

**Comment by josuf107** [comment]
I guess for teams we'll want to display both MiiNames?

**Comment by Xiocious** [comment]
Yeah, but that could be seen with !team [name] too. It would be nice to have (MiiName & MiiName) after it though.

**Comment by josuf107** [comment]
Do we want this in the !list output as well? @Xiocious

**Comment by Xiocious** [comment]
Yes please

**Comment by josuf107** [comment]
Oops forgot !list

**Comment by josuf107** [comment]
We did it.
